### PR TITLE
Add blend order per layer to fix points order

### LINKED ISSUE #30: [Tangram R&D] Layers order doesn't match
The layers order doesn't match with the raster version.

[Raster](https://team.carto.com/u/saleiva/builder/8123f4ff-52eb-4b9e-81dc-5ecf69469f9f/embed?state=%7B%22map%22%3A%7B%22ne%22%3A%5B40.49918094806632%2C-74.06106948852539%5D%2C%22sw%22%3A%5B40.66709790906187%2C-73.89627456665039%5D%7D%2C%22widgets%22%3A%7B%2239ee0c57-74b9-433e-9daf-4d75605c97a9%22%3A%7B%22normalized%22%3Atrue%7D%2C%229bc213fd-c89b-43eb-bbb9-1e3a35c11d3b%22%3A%7B%22normalized%22%3Atrue%7D%2C%22135e059f-30e6-491f-affe-873050e2a5aa%22%3A%7B%22normalized%22%3Atrue%7D%7D%7D) vs [Vector](https://team.carto.com/u/saleiva/builder/8123f4ff-52eb-4b9e-81dc-5ecf69469f9f/embed?vector=true&state=%7B%22map%22%3A%7B%22ne%22%3A%5B40.49918094806632%2C-74.06106948852539%5D%2C%22sw%22%3A%5B40.66709790906187%2C-73.89627456665039%5D%7D%2C%22widgets%22%3A%7B%2239ee0c57-74b9-433e-9daf-4d75605c97a9%22%3A%7B%22normalized%22%3Atrue%7D%2C%229bc213fd-c89b-43eb-bbb9-1e3a35c11d3b%22%3A%7B%22normalized%22%3Atrue%7D%2C%22135e059f-30e6-491f-affe-873050e2a5aa%22%3A%7B%22normalized%22%3Atrue%7D%7D%7D)

The cause is that with the overlay blend type the points goes behind the polygons, so the order have to be setted in the style layer.

cc/ @saleiva

### PR DESCRIPTION
**Pull request by donflopez**
Fix #30

### CODE REVIEW

File: src/basic/lines.js [hunk 1]
```diff
@@ -129,14 +129,14 @@ Line.getDraw = (c3ss, id) => {
...
-Line.getStyle = function(c3ss, id) {
+Line.getStyle = function(c3ss, id, ord) {
   let style = {};
 
   style['lines_' + id] = {
     base: 'lines',
     blend: getBlending(c3ss),
     dash: getDashed(c3ss),
-    blend_order: 2
+    blend_order: isFinite(ord) ? ord + 1 : 1
```
Comment (dgaubert) [inline src/basic/lines.js]: Why do we have a different initialization of `blend_order` for lines? Other symbolizers have `blend_order: ord || 1`.

File: src/style/colors.js [hunk 2]
```diff
@@ -84,7 +84,7 @@ Colors.getAlphaColor = function (color, opacity) {
 		return Utils.functionString(
 				`function () {
           var op = ${opacity}();
-					return ${C.getAlphaColorFn}(${color}(), isFinite(op) ? op : 1);
+					return ${C.getAlphaColorFn}(${color}(), typeof op === "number" ? op : 1);
```
Comment (dgaubert) [inline src/style/colors.js]: Be careful, tabs and spaces mixed

File: src/basic/lines.js (hunk 1 above)
Comment (donflopez) [inline src/basic/lines.js]: Because the lines have to be one step above the others draw elements of his layer, in other case polygons and points are gonna hide them

File: src/style/colors.js (hunk 2 above)
Comment (donflopez) [inline src/style/colors.js]: Oooops, fuck editor :(. Thanks!!

File: src/basic/lines.js (hunk 1 above)
Comment (dgaubert) [inline src/basic/lines.js]: Hum! So for one layer we can mix, for example, lines and polygons. can't we?

Comment (donflopez) [inline src/basic/lines.js]: Yes! For example, Tangram to draw polygons lines takes the lines as a separate shape, so it has to be ordered above the polygon fill.

**Comment by donflopez** [comment]
Yes @dgaubert, my bad! I don't usually think about it... I'll take in mind! Thanks

File: src/basic/lines.js (hunk 1 above)
Comment (dgaubert) [inline src/basic/lines.js]: Good to know! Thanks
